export default {
  LOAD_PLAYLIST_REQUEST: 'LOAD_PLAYLIST_REQUEST',
  LOAD_PLAYLIST_SUCCESS: 'LOAD_PLAYLIST_SUCCESS',
  LOAD_PLAYLIST_FAILED: 'LOAD_PLAYLIST_FAILED',
  SEARCH_YOUTUBE_REQUEST: 'SEARCH_YOUTUBE_REQUEST',
  SEARCH_YOUTUBE_SUCCESS: 'SEARCH_YOUTUBE_SUCCESS',
  SEARCH_YOUTUBE_FAILED: 'SEARCH_YOUTUBE_FAILED'
}
